#!/usr/bin/env node
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const CLAUDE = join(ROOT, "CLAUDE.md");
const EXTS = [".ts", ".tsx", ".scss", ".css", ".rs"];

const TEMPLATE = [
	"Add this section to CLAUDE.md (contents are regenerated by this script):",
	"",
	"# warpcore - Project Structure",
	"",
	"```filelist",
	"```",
	"",
].join("\n");

if (!existsSync(CLAUDE)) {
	console.error(`CLAUDE.md not found at ${CLAUDE}\n\n${TEMPLATE}`);
	process.exit(1);
}

const original = readFileSync(CLAUDE, "utf8");
const fence = /^```filelist$[\s\S]*?^```$/m;

if (!fence.test(original)) {
	console.error(`No filelist section found in ${CLAUDE}\n\n${TEMPLATE}`);
	process.exit(1);
}

// tracked + untracked, minus anything ignored
const tracked = execFileSync(
	"git",
	["ls-files", "--cached", "--others", "--exclude-standard", "--", "packages/"],
	{ cwd: ROOT, encoding: "utf8", maxBuffer: 32 * 1024 * 1024 },
)
	.split("\n")
	.filter((f) => EXTS.some((ext) => f.endsWith(ext)));

const newNode = () => ({ files: [], dirs: {} });

const insert = (node, parts) => {
	if (parts.length === 1) {
		node.files.push(parts[0]);
		return;
	}
	const head = parts[0];
	if (!node.dirs[head]) node.dirs[head] = newNode();
	insert(node.dirs[head], parts.slice(1));
};

const render = (node, depth, out) => {
	const pad = "  ".repeat(depth);
	for (const f of node.files.sort()) out.push(`${pad}- ${f}`);
	for (const d of Object.keys(node.dirs).sort()) {
		out.push(`${pad}- ${d}/`);
		render(node.dirs[d], depth + 1, out);
	}
};

const describe = (pkg) => {
	const pkgJson = join(ROOT, "packages", pkg, "package.json");
	if (!existsSync(pkgJson)) return "";
	try {
		return JSON.parse(readFileSync(pkgJson, "utf8")).description || "";
	} catch {
		return "";
	}
};

const trees = {};

for (const file of tracked) {
	const parts = file.split("/").slice(1);
	if (parts.length < 2) continue;
	const pkg = parts[0];
	if (!trees[pkg]) trees[pkg] = newNode();
	insert(trees[pkg], parts.slice(1));
}

const packages = Object.keys(trees).sort();

if (packages.length === 0) {
	console.error("No source files found. Aborting.");
	process.exit(1);
}

const out = [];

for (const pkg of packages) {
	out.push(`## packages/${pkg}`);
	const desc = describe(pkg);
	if (desc) out.push(desc);
	render(trees[pkg], 0, out);
}

const block = "```filelist\n" + out.join("\n") + "\n```";

writeFileSync(
	CLAUDE,
	original.replace(fence, () => block),
	"utf8",
);
console.log(`CLAUDE.md updated (${packages.length} packages, ${tracked.length} files).`);
